defaults:
  - Dataset: cifar100
  - Architecture: effnet_cifar10_std
  - Ensemble: ensemble_params
  - Quantization: qunatization_params
  - Training: training_params
  - _self_
params:
  data_path: ./data  # path to the training data


